using Dalamud.Interface.Windowing;
using Dalamud.Bindings.ImGui;
using MairsTrivia.Plugin.Api;
using MairsTrivia.QuestionSets;
using System.Numerics;

namespace MairsTrivia.Plugin.Windows;
public sealed class MainWindow : Window, IDisposable
{
    private readonly Plugin plugin; private string serverPassword="", userPassword="", status="Disconnected", venue="", gameName="", search="", category="", tag="", importPath="", newSetTitle="Untitled Question Set"; private TriviaApiClient? api; private string? accessToken; private HostGameState? game; private Guid? selectedSet;
    public MainWindow(Plugin plugin) : base("Mair's Trivia###MairsTrivia") { this.plugin=plugin; SizeConstraints=new WindowSizeConstraints{MinimumSize=new Vector2(700,500),MaximumSize=new Vector2(1200,1000)}; }
    public override void Draw(){ImGui.PushStyleColor(ImGuiCol.Button,new Vector4(1f,.329f,0,1));ImGui.PushStyleColor(ImGuiCol.Header,new Vector4(1f,.169f,.839f,.55f));if(ImGui.BeginTabBar("tabs")){if(ImGui.BeginTabItem("Game")){DrawGame();ImGui.EndTabItem();}if(ImGui.BeginTabItem("Players")){DrawPlayers();ImGui.EndTabItem();}if(ImGui.BeginTabItem("Questions")){DrawQuestions();ImGui.EndTabItem();}if(ImGui.BeginTabItem("Question Sets")){DrawSets();ImGui.EndTabItem();}if(ImGui.BeginTabItem("Scoring")){DrawScoring();ImGui.EndTabItem();}if(ImGui.BeginTabItem("Settings")){DrawSettings();ImGui.EndTabItem();}ImGui.EndTabBar();}ImGui.PopStyleColor(2);}
    private void DrawSettings(){var backend=plugin.Configuration.BackendUrl;var username=plugin.Configuration.Username;Input("Backend URL",ref backend);Input("Server Password",ref serverPassword,true);Input("Username",ref username);plugin.Configuration.BackendUrl=backend;plugin.Configuration.Username=username;plugin.Configuration.Save();Input("User Password",ref userPassword,true);ImGui.TextDisabled("Usernames are 3-64 letters, numbers, ., _, or -. Passwords need at least 10 characters.");ImGui.TextDisabled("Passwords are used only for this connection and are not saved in plugin configuration.");ImGui.TextColored(new Vector4(1f,.17f,.84f,1f),status);if(ImGui.Button("Connect / Login"))_=Authenticate(false);ImGui.SameLine();if(ImGui.Button("Create Host Account"))_=Authenticate(true);}
    private async Task Authenticate(bool register){try{api?.Dispose();var url=new Uri(plugin.Configuration.BackendUrl);if(url.Scheme is not "https" and not "http")throw new Exception("Backend URL must be HTTP(S).");if(string.IsNullOrWhiteSpace(serverPassword))throw new Exception("Enter the server access password.");if(string.IsNullOrWhiteSpace(plugin.Configuration.Username)||string.IsNullOrWhiteSpace(userPassword))throw new Exception("Enter a username and user password.");api=new TriviaApiClient(url);var health=await api.GetAsync<HealthResponse>("/health",null,CancellationToken.None);await api.PostAsync<object>("/v1/access/validate",new{},null,serverPassword,CancellationToken.None);var path=register?"/v1/auth/register":"/v1/auth/login";var login=await api.PostAsync<LoginResponse>(path,new{username=plugin.Configuration.Username,password=userPassword},null,serverPassword,CancellationToken.None);accessToken=login.AccessToken;plugin.Configuration.RefreshToken=login.RefreshToken;plugin.Configuration.Save();await api.GetAsync<HostProfile>("/v1/me",accessToken,CancellationToken.None);status=$"Connected as {login.User.Username} ({health.Service})";}catch(Exception ex){status=ex.Message;}}
    private void DrawGame(){ImGui.Text("Create or manage a host game");Input("Venue Name",ref venue);Input("Game Name",ref gameName);ImGui.Text("Question set: "+(selectedSet?.ToString()??"Select one in Question Sets"));if(ImGui.RadioButton("In Order",plugin.Configuration.CompactUi))plugin.Configuration.CompactUi=true;ImGui.SameLine();if(ImGui.RadioButton("Shuffle Once",!plugin.Configuration.CompactUi))plugin.Configuration.CompactUi=false;if(ImGui.Button("Create Game"))_=CreateGame();if(game is not null){ImGui.Separator();ImGui.Text($"{game.VenueName} — {game.GameName}");ImGui.Text($"Join code: {game.JoinCode}");ImGui.TextWrapped($"Player URL: {game.PlayerUrl}");if(ImGui.Button("Copy Link"))ImGui.SetClipboardText(game.PlayerUrl);ImGui.Text($"State: {game.State}");}}
    private async Task CreateGame(){try{if(api is null||accessToken is null)throw new Exception("Connect first.");if(string.IsNullOrWhiteSpace(venue)||string.IsNullOrWhiteSpace(gameName)||selectedSet is null)throw new Exception("Venue Name, Game Name, and question set are required.");var set=plugin.Library.Load(selectedSet.Value);game=await api.PostAsync<HostGameState>("/v1/games",new CreateGameRequest(venue,gameName,set,plugin.Configuration.CompactUi?"inOrder":"shuffleOnce",new(plugin.Configuration.CorrectPoints,plugin.Configuration.IncorrectPoints,plugin.Configuration.FirstCorrectBonus)),accessToken,null,CancellationToken.None);status="Game created.";}catch(Exception ex){status=ex.Message;}}
    private void DrawPlayers(){if(game is null){ImGui.TextDisabled("Create or resume a game first.");return;}ImGui.Text($"Players: {game.Players.Count}");foreach(var p in game.Players)ImGui.BulletText($"{p.DisplayName}: {p.Score} points — ✓ {p.CorrectCount} / ✗ {p.IncorrectCount}");}
    private void DrawQuestions(){if(game is null){ImGui.TextDisabled("No active game.");return;}ImGui.Text("Preview is host-only; the backend sends players only opaque choices.");if(ImGui.Button("Preview Next"))_=Command("questions/preview");ImGui.SameLine();if(ImGui.Button("Send Question"))_=Command("questions/open");ImGui.SameLine();if(ImGui.Button("Skip Question"))_=Command("questions/skip");ImGui.SameLine();if(ImGui.Button("Close / Results"))_=Command("questions/close");ImGui.SameLine();if(ImGui.Button("End Game"))_=Command("end");ImGui.Text("First correct responder and answer order are determined by the backend.");}
    private async Task Command(string suffix){try{if(api is null||accessToken is null||game is null)throw new Exception("No connected game.");await api.PostAsync<object>($"/v1/games/{game.Id}/"+suffix,new{},accessToken,null,CancellationToken.None);game=await api.GetAsync<HostGameState>($"/v1/games/{game.Id}",accessToken,CancellationToken.None);status="Command sent.";}catch(Exception ex){status=ex.Message;}}
    private void DrawSets(){Input("Search",ref search);Input("Category filter",ref category);Input("Tag filter",ref tag);Input("Import file path",ref importPath);if(ImGui.Button("Import .fftrivia")){try{var set=plugin.Library.Import(importPath);selectedSet=set.Id;status=$"Imported and copied: {set.Title}";}catch(Exception ex){status=ex.Message;}}ImGui.SameLine();Input("New set title",ref newSetTitle);if(ImGui.Button("Create Set")){try{var set=plugin.Library.Create(newSetTitle);selectedSet=set.Id;status="Created a new local set. Add valid questions before use.";}catch(Exception ex){status=ex.Message;}}foreach(var entry in plugin.Library.Search(search,category,tag)){var selected=selectedSet==entry.Id;if(ImGui.Selectable(entry.Title,selected)){selectedSet=entry.Id;status=entry.Description;}ImGui.SameLine();if(game is not null&&ImGui.SmallButton("Use##"+entry.Id))_=Command($"question-sets/{entry.Id}/select");ImGui.SameLine();if(ImGui.SmallButton("Delete##"+entry.Id)){plugin.Library.Delete(entry.Id);if(selected)selectedSet=null;}}ImGui.TextWrapped(status);}
    private void DrawScoring(){var correct=plugin.Configuration.CorrectPoints;var incorrect=plugin.Configuration.IncorrectPoints;var first=plugin.Configuration.FirstCorrectBonus;if(ImGui.InputInt("Correct points",ref correct))plugin.Configuration.CorrectPoints=correct;if(ImGui.InputInt("Incorrect points",ref incorrect))plugin.Configuration.IncorrectPoints=incorrect;if(ImGui.InputInt("First-correct bonus",ref first))plugin.Configuration.FirstCorrectBonus=first;plugin.Configuration.Save();}
    private static void Input(string label,ref string value,bool password=false){ImGui.InputText(label,ref value,256,password?ImGuiInputTextFlags.Password:ImGuiInputTextFlags.None);} public void Dispose()=>api?.Dispose();
}
