using Microsoft.Win32;
using MairsTrivia.QuestionSets;
using System.ComponentModel;
using System.IO;
using System.Windows;
using System.Windows.Controls;

namespace MairsTrivia.Editor;
public partial class MainWindow : Window
{
    private QuestionSet _set = new(); private string? _path; private bool _dirty; private TriviaQuestion? _selected;
    public MainWindow() { InitializeComponent(); NewDocument(); }
    private static List<string> Split(string text) => text.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries).ToList();
    private void NewDocument() { _set = new(); _path = null; _selected = null; LoadSet(); _dirty = false; UpdateTitle(); }
    private void LoadSet() { TitleBox.Text=_set.Title; AuthorBox.Text=_set.Author; VersionBox.Text=_set.Version; CategoriesBox.Text=string.Join(", ",_set.Categories); TagsBox.Text=string.Join(", ",_set.Tags); DescriptionBox.Text=_set.Description; RefreshList(); LoadQuestion(null); }
    private void CommitSet() { _set.Title=TitleBox.Text;_set.Author=AuthorBox.Text;_set.Version=VersionBox.Text;_set.Categories=Split(CategoriesBox.Text);_set.Tags=Split(TagsBox.Text);_set.Description=DescriptionBox.Text; if(_selected is not null){_selected.Question=QuestionBox.Text;_selected.CorrectAnswer=CorrectBox.Text;_selected.IncorrectAnswers=IncorrectAnswers.Children.OfType<TextBox>().Select(x=>x.Text).ToList();_selected.Category=string.IsNullOrWhiteSpace(QuestionCategoryBox.Text)?null:QuestionCategoryBox.Text;_selected.Tags=Split(QuestionTagsBox.Text);} }
    private void RefreshList() { CommitSetMetadata(); var term=SearchBox.Text.Trim(); var category=CategoryFilterBox.Text.Trim();var tag=TagFilterBox.Text.Trim(); QuestionList.ItemsSource=_set.Questions.Where(q=>(string.IsNullOrEmpty(term)||$"{q.Question} {q.CorrectAnswer} {string.Join(' ',q.IncorrectAnswers)} {q.Category} {string.Join(' ',q.Tags)}".Contains(term,StringComparison.OrdinalIgnoreCase))&&(string.IsNullOrEmpty(category)||string.Equals(q.Category,category,StringComparison.OrdinalIgnoreCase))&&(string.IsNullOrEmpty(tag)||q.Tags.Any(t=>string.Equals(t,tag,StringComparison.OrdinalIgnoreCase)))).ToList(); }
    private void CommitSetMetadata(){_set.Title=TitleBox.Text;_set.Author=AuthorBox.Text;_set.Version=VersionBox.Text;_set.Categories=Split(CategoriesBox.Text);_set.Tags=Split(TagsBox.Text);_set.Description=DescriptionBox.Text;}
    private void LoadQuestion(TriviaQuestion? q){_selected=q;QuestionBox.Text=q?.Question??"";CorrectBox.Text=q?.CorrectAnswer??"";IncorrectAnswers.Children.Clear();foreach(var answer in q?.IncorrectAnswers??Enumerable.Repeat("",9))IncorrectAnswers.Children.Add(new TextBox{Text=answer,Margin=new Thickness(3)});QuestionCategoryBox.Text=q?.Category??"";QuestionTagsBox.Text=string.Join(", ",q?.Tags??[]);}
    private void Dirty(object? s, EventArgs e){_dirty=true;UpdateTitle();} private void IncorrectChanged(object s,TextChangedEventArgs e)=>Dirty(s,e); private void UpdateTitle()=>Title=$"{(_dirty?"* ":"")}Mair's Trivia Question Set Editor{(_path is null?"":" — "+Path.GetFileName(_path))}";
    private bool ConfirmDiscard()=>!_dirty||MessageBox.Show("You have unsaved changes. Discard them?","Unsaved changes",MessageBoxButton.YesNo,MessageBoxImage.Warning)==MessageBoxResult.Yes;
    private void New_Click(object s,RoutedEventArgs e){if(ConfirmDiscard())NewDocument();} private void Open_Click(object s,RoutedEventArgs e){if(!ConfirmDiscard())return;var d=new OpenFileDialog{Filter="Mair's Trivia sets (*.fftrivia)|*.fftrivia|JSON files (*.json)|*.json"};if(d.ShowDialog()==true)LoadFile(d.FileName);} private void Import_Click(object s,RoutedEventArgs e)=>Open_Click(s,e);
    private void LoadFile(string path){try{var loaded=QuestionSetSerializer.Load(path);var issues=QuestionSetValidator.Validate(loaded);if(issues.Count>0)throw new QuestionSetFormatException(string.Join("\n",issues.Select(x=>$"{x.Path}: {x.Message}")));_set=loaded;_path=path;LoadSet();_dirty=false;UpdateTitle();}catch(Exception ex){MessageBox.Show(ex.Message,"Cannot open question set",MessageBoxButton.OK,MessageBoxImage.Error);}}
    private void Save_Click(object s,RoutedEventArgs e){if(_path is null){SaveAs_Click(s,e);return;}SaveTo(_path);} private void SaveAs_Click(object s,RoutedEventArgs e){var d=new SaveFileDialog{Filter="Mair's Trivia sets (*.fftrivia)|*.fftrivia",DefaultExt=".fftrivia",FileName=_set.Title};if(d.ShowDialog()==true)SaveTo(d.FileName);} private void Export_Click(object s,RoutedEventArgs e)=>SaveAs_Click(s,e);
    private void SaveTo(string path){CommitSet();var issues=QuestionSetValidator.Validate(_set);if(issues.Count>0){MessageBox.Show(string.Join("\n",issues.Select(x=>$"{x.Path}: {x.Message}")),"Cannot save invalid set",MessageBoxButton.OK,MessageBoxImage.Warning);return;}QuestionSetSerializer.Save(path,_set);_path=path;_dirty=false;UpdateTitle();StatusText.Text="Saved and validated.";}
    private void Validate_Click(object s,RoutedEventArgs e){CommitSet();var issues=QuestionSetValidator.Validate(_set);MessageBox.Show(issues.Count==0?"Question set is valid.":string.Join("\n",issues.Select(x=>$"{x.Path}: {x.Message}")),"Validation",MessageBoxButton.OK,issues.Count==0?MessageBoxImage.Information:MessageBoxImage.Warning);}
    private void QuestionSelected(object s,SelectionChangedEventArgs e){CommitSet();LoadQuestion(QuestionList.SelectedItem as TriviaQuestion);} private void FilterChanged(object s,TextChangedEventArgs e)=>RefreshList();
    private void Add_Click(object s,RoutedEventArgs e){CommitSet();var q=new TriviaQuestion();_set.Questions.Add(q);RefreshList();QuestionList.SelectedItem=q;LoadQuestion(q);Dirty(s,e);} private void Edit_Click(object s,RoutedEventArgs e)=>QuestionBox.Focus(); private void Duplicate_Click(object s,RoutedEventArgs e){CommitSet();if(_selected is null)return;var copy=_selected.Copy();_set.Questions.Insert(_set.Questions.IndexOf(_selected)+1,copy);RefreshList();QuestionList.SelectedItem=copy;Dirty(s,e);} private void Delete_Click(object s,RoutedEventArgs e){if(_selected is null)return;_set.Questions.Remove(_selected);RefreshList();LoadQuestion(null);Dirty(s,e);} private void Up_Click(object s,RoutedEventArgs e)=>Move(-1);private void Down_Click(object s,RoutedEventArgs e)=>Move(1);private void Move(int d){CommitSet();if(_selected is null)return;var i=_set.Questions.IndexOf(_selected);var n=i+d;if(n<0||n>=_set.Questions.Count)return;_set.Questions.RemoveAt(i);_set.Questions.Insert(n,_selected);RefreshList();QuestionList.SelectedItem=_selected;Dirty(this,EventArgs.Empty);}
    private void OnClosing(object s,CancelEventArgs e){if(!ConfirmDiscard())e.Cancel=true;}
}
