import argon2 from "argon2";
import { createHash, createHmac, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import { EventEmitter } from "node:events";
import type { TriviaDb } from "./db.js";
import type { Config } from "./config.js";
import { hasValidAnswerSet, type QuestionSet, type TriviaQuestion } from "./shared/question-set.js";

type GameRow = { id:string; owner_user_id:string; join_code:string; venue_name:string; game_name:string; state:string; scoring_json:string; active_set_id:string|null; active_question_id:string|null; created_at:string; updated_at:string };
const now = () => new Date().toISOString(); const hash = (s:string) => createHash("sha256").update(s).digest("hex");
const secret = () => randomBytes(32).toString("base64url"); const json = <T>(s:string) => JSON.parse(s) as T;
export class ServiceError extends Error { constructor(public status:number, public code:string, message:string) { super(message); } }
export interface Scoring { correctPoints:number; incorrectPoints:number; firstCorrectBonus:number; secondCorrectBonus?:number; thirdCorrectBonus?:number; allowAnswerChange:boolean; }
const defaultScoring: Scoring = { correctPoints: 100, incorrectPoints: 0, firstCorrectBonus: 50, allowAnswerChange: false };

export class TriviaService {
  readonly events = new EventEmitter();
  constructor(private db:TriviaDb, private config:Config) {}
  private fail(status:number, code:string, message:string): never { throw new ServiceError(status, code, message); }
  private changed(gameId:string) { this.events.emit("game", gameId); }
  verifyServerAccess(value: unknown) { const given = Buffer.from(String(value ?? "")); const expected = Buffer.from(this.config.serverAccessPassword); return given.length === expected.length && timingSafeEqual(given, expected); }
  private issueAccess(userId:string, sessionId:string) { const payload = Buffer.from(JSON.stringify({ sub:userId, sid:sessionId, exp:Date.now()+15*60_000 })).toString("base64url"); return `${payload}.${createHmac("sha256",this.config.tokenSecret).update(payload).digest("base64url")}`; }
  private parseAccess(token:string) { const [payload, signature] = token.split("."); if (!payload || !signature || !timingSafeEqual(Buffer.from(signature), Buffer.from(createHmac("sha256",this.config.tokenSecret).update(payload).digest("base64url")))) this.fail(401,"invalid_token","Access token is invalid."); const value=json<{sub:string;sid:string;exp:number}>(Buffer.from(payload,"base64url").toString()); if (value.exp < Date.now()) this.fail(401,"expired_token","Access token has expired."); const session=this.db.prepare("SELECT revoked_at, expires_at FROM sessions WHERE id=? AND user_id=?").get(value.sid,value.sub) as {revoked_at:string|null;expires_at:string}|undefined; if (!session || session.revoked_at || session.expires_at < now()) this.fail(401,"revoked_token","Session is no longer active."); return value.sub; }
  authenticate(token:string|undefined) { if (!token) this.fail(401,"missing_token","Host authentication is required."); return this.parseAccess(token); }
  async register(username:string,password:string) { if (!this.config.registrationEnabled) this.fail(403,"registration_disabled","Registration is disabled."); if (!/^[\w.-]{3,64}$/.test(username)) this.fail(400,"invalid_username","Username must be 3-64 letters, numbers, periods, underscores, or hyphens."); const id=randomUUID(); try { this.db.prepare("INSERT INTO users VALUES(?,?,?,?)").run(id,username,await argon2.hash(password,{type:argon2.argon2id}),now()); } catch { this.fail(409,"username_taken","That username is already registered."); } return this.login(username,password); }
  async login(username:string,password:string) { const user=this.db.prepare("SELECT * FROM users WHERE username=?").get(username) as {id:string;username:string;password_hash:string;created_at:string}|undefined; if (!user || !await argon2.verify(user.password_hash,password)) this.fail(401,"invalid_login","Username or password is incorrect."); const refreshToken=secret(), sessionId=randomUUID(); this.db.prepare("INSERT INTO sessions VALUES(?,?,?,?,?,?)").run(sessionId,user.id,hash(refreshToken),new Date(Date.now()+30*86400_000).toISOString(),null,now()); return { accessToken:this.issueAccess(user.id,sessionId), refreshToken, user:{id:user.id,username:user.username,createdAt:user.created_at} }; }
  refresh(refreshToken:string) { const row=this.db.prepare("SELECT * FROM sessions WHERE refresh_hash=? AND revoked_at IS NULL AND expires_at>? ").get(hash(refreshToken),now()) as {id:string;user_id:string}|undefined; if (!row) this.fail(401,"invalid_refresh","Refresh credential is invalid."); const replacement=secret(); this.db.prepare("UPDATE sessions SET refresh_hash=? WHERE id=?").run(hash(replacement),row.id); return {accessToken:this.issueAccess(row.user_id,row.id),refreshToken:replacement}; }
  logout(token:string) { const [,p]=token.split("."); const payload=token.split(".")[0]; if (!p||!payload) return; try { const v=json<{sid:string}>(Buffer.from(payload,"base64url").toString()); this.db.prepare("UPDATE sessions SET revoked_at=? WHERE id=?").run(now(),v.sid); } catch { /* idempotent */ } }
  me(userId:string) { const u=this.db.prepare("SELECT id,username,created_at FROM users WHERE id=?").get(userId) as {id:string;username:string;created_at:string}; return {id:u.id,username:u.username,createdAt:u.created_at}; }
  private gameForOwner(owner:string,id:string) { const game=this.db.prepare("SELECT * FROM games WHERE id=? AND owner_user_id=?").get(id,owner) as GameRow|undefined; if (!game) this.fail(404,"game_not_found","Game was not found."); return game; }
  listGames(owner:string) { return (this.db.prepare("SELECT id,join_code,venue_name,game_name,state,created_at,updated_at FROM games WHERE owner_user_id=? ORDER BY created_at DESC").all(owner) as any[]).map(g=>({id:g.id,joinCode:g.join_code,venueName:g.venue_name,gameName:g.game_name,state:g.state,createdAt:g.created_at,updatedAt:g.updated_at})); }
  createGame(owner:string,input:{venueName:string;gameName:string;questionSet:QuestionSet;orderingMode:"inOrder"|"shuffleOnce";scoring?:Partial<Scoring>}) { if (!input.venueName?.trim()||!input.gameName?.trim()) this.fail(400,"game_name_required","Venue Name and Game Name are required."); this.validateSet(input.questionSet); const id=randomUUID(), joinCode=this.joinCode(), setId=randomUUID(), created=now(), scoring={...defaultScoring,...input.scoring}; const questions=[...input.questionSet.questions]; if(input.orderingMode==="shuffleOnce") this.shuffle(questions); const queue=questions.map(q=>q.id); this.db.transaction(()=>{ this.db.prepare("INSERT INTO games VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run(id,owner,joinCode,input.venueName.trim(),input.gameName.trim(),"lobby",JSON.stringify(scoring),setId,null,created,created,null); this.insertSet(id,setId,input.questionSet,input.orderingMode,queue,created); this.history(id,"game.created",{venueName:input.venueName,gameName:input.gameName}); })(); return this.hostState(owner,id); }
  private joinCode() { let code=""; do { code=randomBytes(5).toString("base64url").replace(/[-_]/g,"A").slice(0,6).toUpperCase(); } while(this.db.prepare("SELECT 1 FROM games WHERE join_code=?").get(code)); return code; }
  private validateSet(set:QuestionSet) { const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;const text=(v:unknown)=>typeof v==="string"&&v.trim().length>0;const list=(v:unknown)=>Array.isArray(v)&&v.every(text)&&new Set(v.map(x=>x.trim().toLowerCase())).size===v.length;const minimum=set?.schemaVersion===1?9:3;if (!set || set.format!=="fftrivia-question-set"||![1,2].includes(set.schemaVersion)||!uuid.test(set.id)||!text(set.title)||typeof set.description!=="string"||!text(set.author)||!text(set.version)||!list(set.categories)||!list(set.tags)||!Array.isArray(set.questions)||!set.questions.every(q=>uuid.test(q.id)&&text(q.question)&&hasValidAnswerSet(q,minimum,9)&&list(q.tags)&&(q.category===null||text(q.category)))) this.fail(400,"invalid_question_set","Question set does not meet the .fftrivia contract."); }
  private insertSet(gameId:string,id:string,set:QuestionSet,ordering:string,queue:string[],created:string) { this.db.prepare("INSERT INTO game_question_sets VALUES(?,?,?,?,?,?,?,?)").run(id,gameId,set.id,set.title,JSON.stringify(set),ordering,JSON.stringify(queue),created); const ins=this.db.prepare("INSERT INTO game_question_state VALUES(?,?,?,?,?,?,?,?)"); queue.forEach((q,index)=>ins.run(randomUUID(),id,q,"unused",index,null,null,null)); }
  private history(gameId:string,event:string,payload:unknown) { this.db.prepare("INSERT INTO game_history VALUES(?,?,?,?,?)").run(randomUUID(),gameId,event,JSON.stringify(payload),now()); }
  hostState(owner:string,id:string) { const g=this.gameForOwner(owner,id); const players=this.db.prepare("SELECT id,display_name,score,correct_count,incorrect_count FROM players WHERE game_id=? ORDER BY score DESC,joined_at").all(id) as any[]; return {id:g.id,joinCode:g.join_code,playerUrl:`${this.config.publicBaseUrl}/play/${g.join_code}`,venueName:g.venue_name,gameName:g.game_name,state:g.state,scoring:json(g.scoring_json),activeSetId:g.active_set_id,activeQuestionId:g.active_question_id,players:players.map(p=>({id:p.id,displayName:p.display_name,score:p.score,correctCount:p.correct_count,incorrectCount:p.incorrect_count}))}; }
  addSet(owner:string,gameId:string,set:QuestionSet,ordering:"inOrder"|"shuffleOnce") { const g=this.gameForOwner(owner,gameId); this.validateSet(set); const existing=this.db.prepare("SELECT id FROM game_question_sets WHERE game_id=? AND source_set_id=?").get(g.id,set.id) as {id:string}|undefined; if(existing)return {gameSetId:existing.id,reused:true}; const questions=[...set.questions];if(ordering==="shuffleOnce")this.shuffle(questions);const id=randomUUID();this.db.transaction(()=>{this.insertSet(g.id,id,set,ordering,questions.map(q=>q.id),now());this.history(g.id,"questionSet.added",{sourceSetId:set.id});})();return {gameSetId:id,reused:false}; }
  selectSet(owner:string,gameId:string,setId:string) { const g=this.gameForOwner(owner,gameId);if(g.state==="question_open")this.fail(409,"question_open","Question set cannot change while answers are open.");const set=this.db.prepare("SELECT id FROM game_question_sets WHERE id=? AND game_id=?").get(setId,g.id);if(!set)this.fail(404,"question_set_not_found","Question set is not attached to this game.");this.db.prepare("UPDATE games SET active_set_id=?, state=?, updated_at=? WHERE id=?").run(setId,"lobby",now(),g.id);this.history(g.id,"questionSet.selected",{gameSetId:setId});this.changed(g.id);return this.hostState(owner,g.id); }
  preview(owner:string,gameId:string) { const g=this.gameForOwner(owner,gameId);if(!g.active_set_id)this.fail(409,"no_question_set","Select a question set first.");if(!["lobby","results"].includes(g.state))this.fail(409,"invalid_state","A question cannot be previewed now.");let q=this.db.prepare("SELECT * FROM game_question_state WHERE game_set_id=? AND state='previewed' ORDER BY ordinal LIMIT 1").get(g.active_set_id) as any;if(!q)q=this.db.prepare("SELECT * FROM game_question_state WHERE game_set_id=? AND state='unused' ORDER BY ordinal LIMIT 1").get(g.active_set_id) as any;if(!q)this.fail(409,"no_questions","No unused questions remain.");this.db.prepare("UPDATE game_question_state SET state='previewed',previewed_at=? WHERE id=?").run(now(),q.id);this.db.prepare("UPDATE games SET state='preview',active_question_id=?,updated_at=? WHERE id=?").run(q.question_id,now(),g.id);return this.questionForHost(g,q.question_id); }
  private questionForHost(g:GameRow,qid:string) { const set=this.db.prepare("SELECT set_json FROM game_question_sets WHERE id=?").get(g.active_set_id!) as {set_json:string};return (json<QuestionSet>(set.set_json).questions.find(q=>q.id===qid))!; }
  skip(owner:string,gameId:string) { const g=this.gameForOwner(owner,gameId);if(g.state!=="preview"||!g.active_set_id||!g.active_question_id)this.fail(409,"invalid_state","Only a previewed question can be skipped.");this.db.transaction(()=>{this.db.prepare("UPDATE game_question_state SET state='skipped' WHERE game_set_id=? AND question_id=?").run(g.active_set_id,g.active_question_id);this.db.prepare("INSERT INTO skipped_questions VALUES(?,?,?,?,?)").run(randomUUID(),g.id,g.active_set_id,g.active_question_id,now());this.db.prepare("UPDATE games SET state='lobby',active_question_id=NULL,updated_at=? WHERE id=?").run(now(),g.id);this.history(g.id,"question.skipped",{questionId:g.active_question_id});})();this.changed(g.id); }
  open(owner:string,gameId:string) { const g=this.gameForOwner(owner,gameId);if(g.state!=="preview"||!g.active_question_id)this.fail(409,"invalid_state","Preview a question before opening it.");const question=this.questionForHost(g,g.active_question_id);const players=this.db.prepare("SELECT id FROM players WHERE game_id=?").all(g.id) as {id:string}[];this.db.transaction(()=>{for(const p of players)this.layout(p.id,g.id,question);this.db.prepare("UPDATE game_question_state SET state='asked',asked_at=? WHERE game_set_id=? AND question_id=?").run(now(),g.active_set_id,g.active_question_id);this.db.prepare("UPDATE games SET state='question_open',updated_at=? WHERE id=?").run(now(),g.id);this.history(g.id,"question.opened",{questionId:g.active_question_id});})();this.changed(g.id); }
  private layout(playerId:string,gameId:string,q:TriviaQuestion) { const selected=this.shuffle([...q.incorrectAnswers]).slice(0,3);const answers=this.shuffle([q.correctAnswer,...selected]).map(text=>({id:secret(),text}));const correct=answers.find(a=>a.text===q.correctAnswer)!;this.db.prepare("INSERT OR IGNORE INTO player_question_layouts VALUES(?,?,?,?,?,?,?)").run(randomUUID(),playerId,gameId,q.id,JSON.stringify(answers),correct.id,now()); }
  join(joinCode:string,displayName:string) { const g=this.db.prepare("SELECT * FROM games WHERE join_code=? AND state!='finished'").get(joinCode) as GameRow|undefined;if(!g)this.fail(404,"game_not_found","That game is unavailable.");if(!displayName?.trim()||displayName.length>48)this.fail(400,"invalid_display_name","Enter a display name up to 48 characters.");const id=randomUUID(),reconnect=secret();this.db.prepare("INSERT INTO players VALUES(?,?,?,?,?,?,?,?,?)").run(id,g.id,displayName.trim(),hash(reconnect),0,0,0,now(),now());this.changed(g.id);return {playerId:id,reconnectToken:reconnect,game:this.playerState(g,id)}; }
  playerReconnect(token:string) { const p=this.db.prepare("SELECT * FROM players WHERE reconnect_hash=?").get(hash(token)) as {id:string;game_id:string}|undefined;if(!p)this.fail(401,"invalid_player_session","Player reconnect credential is invalid.");this.db.prepare("UPDATE players SET last_seen_at=? WHERE id=?").run(now(),p.id);const g=this.db.prepare("SELECT * FROM games WHERE id=?").get(p.game_id) as GameRow;return {playerId:p.id,gameId:p.game_id,game:this.playerState(g,p.id)}; }
  private playerState(g:GameRow,playerId:string) { const p=this.db.prepare("SELECT display_name,score,correct_count,incorrect_count FROM players WHERE id=?").get(playerId) as any;let question:unknown=null,result:unknown=null;if(g.active_question_id){const answer=this.db.prepare("SELECT answer_id,is_correct,points_awarded FROM player_answers WHERE player_id=? AND question_id=?").get(playerId,g.active_question_id) as {answer_id:string;is_correct:number;points_awarded:number}|undefined;if(g.state==="question_open"){const l=this.db.prepare("SELECT choices_json FROM player_question_layouts WHERE player_id=? AND question_id=?").get(playerId,g.active_question_id) as {choices_json:string}|undefined;question=l?{id:g.active_question_id,question:this.questionForHost(g,g.active_question_id).question,choices:json(l.choices_json),answerSubmitted:!!answer,selectedAnswerId:answer?.answer_id??null}:null;}else if(g.state==="results"){const source=this.questionForHost(g,g.active_question_id),layout=this.db.prepare("SELECT choices_json FROM player_question_layouts WHERE player_id=? AND question_id=?").get(playerId,g.active_question_id) as {choices_json:string}|undefined;const selected=layout&&answer?json<{id:string;text:string}[]>(layout.choices_json).find(choice=>choice.id===answer.answer_id):undefined;result={question:source.question,correctAnswer:source.correctAnswer,selectedAnswer:selected?.text??null,isCorrect:answer?.is_correct===1,pointsAwarded:answer?.points_awarded??0};}}return {venueName:g.venue_name,gameName:g.game_name,state:g.state,player:{displayName:p.display_name,score:p.score,correctCount:p.correct_count,incorrectCount:p.incorrect_count},question,result}; }
  answer(token:string,questionId:string,answerId:string) { const p=this.db.prepare("SELECT * FROM players WHERE reconnect_hash=?").get(hash(token)) as any;if(!p)this.fail(401,"invalid_player_session","Player session is invalid.");const g=this.db.prepare("SELECT * FROM games WHERE id=?").get(p.game_id) as GameRow;if(g.state!=="question_open"||g.active_question_id!==questionId)this.fail(409,"invalid_state","This question is not accepting answers.");const prior=this.db.prepare("SELECT id FROM player_answers WHERE player_id=? AND question_id=?").get(p.id,questionId);const scoring=json<Scoring>(g.scoring_json);if(prior&&!scoring.allowAnswerChange)this.fail(409,"answer_locked","Your answer is already locked.");const layout=this.db.prepare("SELECT * FROM player_question_layouts WHERE player_id=? AND question_id=?").get(p.id,questionId) as any;if(!layout||!json<{id:string}[]>(layout.choices_json).some(c=>c.id===answerId))this.fail(400,"invalid_answer","That answer is not assigned to this player.");const correct=layout.correct_answer_id===answerId;const receipt=(this.db.prepare("SELECT COALESCE(MAX(receipt_order),0)+1 AS n FROM player_answers WHERE game_id=? AND question_id=?").get(g.id,questionId) as any).n;const firstCorrect=correct&&!this.db.prepare("SELECT 1 FROM player_answers WHERE game_id=? AND question_id=? AND is_correct=1").get(g.id,questionId);let points=correct?scoring.correctPoints:scoring.incorrectPoints;if(firstCorrect)points+=scoring.firstCorrectBonus;const asked=this.db.prepare("SELECT asked_at FROM game_question_state WHERE game_set_id=? AND question_id=?").get(g.active_set_id,questionId) as any;this.db.transaction(()=>{if(prior)this.db.prepare("DELETE FROM player_answers WHERE player_id=? AND question_id=?").run(p.id,questionId);this.db.prepare("INSERT INTO player_answers VALUES(?,?,?,?,?,?,?,?,?,?)").run(randomUUID(),p.id,g.id,questionId,answerId,correct?1:0,receipt,now(),Math.max(0,Date.now()-Date.parse(asked.asked_at)),points);this.db.prepare("UPDATE players SET score=score+?,correct_count=correct_count+?,incorrect_count=incorrect_count+? WHERE id=?").run(points,correct?1:0,correct?0:1,p.id);})();this.changed(g.id);return {accepted:true,locked:!scoring.allowAnswerChange}; }
  close(owner:string,gameId:string) { const g=this.gameForOwner(owner,gameId);if(g.state!=="question_open"||!g.active_question_id)this.fail(409,"invalid_state","No open question exists.");this.db.transaction(()=>{this.db.prepare("UPDATE game_question_state SET state='completed',completed_at=? WHERE game_set_id=? AND question_id=?").run(now(),g.active_set_id,g.active_question_id);this.db.prepare("UPDATE games SET state='results',updated_at=? WHERE id=?").run(now(),g.id);this.history(g.id,"question.closed",{questionId:g.active_question_id});})();this.changed(g.id); }
  end(owner:string,gameId:string) { const g=this.gameForOwner(owner,gameId);if(g.state==="question_open")this.fail(409,"question_open","Close the current question before ending the game.");this.db.prepare("UPDATE games SET state='finished',ended_at=?,updated_at=? WHERE id=?").run(now(),now(),g.id);this.history(g.id,"game.ended",{});this.changed(g.id); }
  private shuffle<T>(items:T[]):T[]{for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]];}return items;}
}
